# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphmize < Formula
  desc "Graphmize is a tool to visualize the dependencies of kustomize."
  homepage "https://github.com/hourglasshoro/graphmize"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.2.0/graphmize_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "9b04970aced3970180f8ea2be104a8d775c36dee05108aad07be5f0276db875b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.2.0/graphmize_0.2.0_Linux_x86_64.tar.gz"
    sha256 "32722ff8b6a28cd19facadfe837fbbc2158fcf2049df8dac2ef77e48a16ab832"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.2.0/graphmize_0.2.0_Linux_arm64.tar.gz"
    sha256 "d1f9dbe6d870bf559c4173de3ec1c95baf64ecfa487d8019f6baa0245e40f8b7"
  end

  def install
    bin.install "graphmize"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
