# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphmize < Formula
  desc "Graphmize is a tool to visualize the dependencies of kustomize."
  homepage "https://github.com/hourglasshoro/graphmize"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.1.1/graphmize_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "5ca159b32e251b7878ca7aeec249fe8cfd18f90b46c92d5aadfbbcb6a1351023"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.1.1/graphmize_0.1.1_Linux_x86_64.tar.gz"
    sha256 "274a3ad183df4fcbae9f4d3154c99425bbb429f1dff7c39a3c2831b361cbdf03"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hourglasshoro/graphmize/releases/download/v0.1.1/graphmize_0.1.1_Linux_arm64.tar.gz"
    sha256 "16aa0a779d743dbc90067271674b2661279b81ced771672ecf18f0d49e0cbc88"
  end

  def install
    bin.install "graphmize"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
